services:
  - type: web
    name: service-point-main
    env: static
    rootDir: main-site
    buildCommand: npm install && npm run build
    staticPublishPath: dist

  - type: web
    name: service-point-admin-app
    env: static
    rootDir: admin-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist

  - type: web
    name: service-point-admin-api
    env: node
    rootDir: admin-backend
    buildCommand: npm install
    startCommand: npm start

  - type: web
    name: service-point-contractor-app
    env: static
    rootDir: contractor-dashboard
    buildCommand: npm install && npm run build
    staticPublishPath: dist
